name: Docker

on:
  workflow_call:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3.6.1

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: programa

      - name: Docker Login
        uses: docker/login-action@v3.3.0
        with:
          username: lucasnoman
          password: ${{ secrets.PASSWORD_DOCKER_HUB }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: lucasnoman/alura-ci:latest${{github.ref_name}}
